#!/bin/bash

dir=`pwd $0`

classpath="${dir}/lib/*"

i=0
while read subdir
do
    subdirs[$i]="${subdir}/lib/*"
    (( i++ ))
done < <(ls -d ${dir}/lib/*/)
subdirs=$( IFS=$':'; echo "${subdirs[*]}" )

classpath="${classpath}:${subdirs}"

java $* -Xms2000M -Dfile.encoding="UTF-8" -Dpidfile.path="ws.pid" -cp "$classpath" play.core.server.ProdServerStart "$dir"