#!/bin/bash

scriptdir=`pwd $0`

classpath="$scriptdir/lib/*"

./start-idx && sleep 3 && ./start-ws $* ./stop-idx

# WEB_APPLICATION_INDEXER_TYPE="ELASTICSEARCH" WEB_APPLICATION_INDEXER_NODETYPE="LOCAL" WEB_APPLICATION_INDEXER_HOSTS="localhost" WEB_APPLICATION_INDEXER_PORTS=9300
# exec java $* -Xms2000M -Dfile.encoding=UTF-8 -Dpidfile.path=ws.pid -cp "$classpath" play.core.server.ProdServerStart $scriptdir