DROP DATABASE IF EXISTS datahare;
DROP DATABASE IF EXISTS test;
CREATE DATABASE datahare;
CREATE DATABASE test;
GRANT ALL PRIVILEGES ON DATABASE datashare TO test;
GRANT ALL PRIVILEGES ON DATABASE test TO test;

