#!/bin/bash

dir=`pwd $0`

classpath="${dir}/lib/datashare-api-0.6.jar:${dir}/lib/datashare-cli-0.6.jar"

PATH=$PATH:"$classpath" \
LD_LIBRARY_PATH="$classpath"${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH} \
DYLD_LIBRARY_PATH="$classpath"${DYLD_LIBRARY_PATH:+:$DYLD_LIBRARY_PATH} \
java -Xms2000M -Dfile.encoding="UTF-8" -cp "$classpath" org.icij.datashare.cli.RemoteFilesCli $*