#!/bin/bash

scriptdir=`pwd $0`

classpath="$scriptdir/lib/*"

export PATH=$PATH:"$classpath"
export LD_LIBRARY_PATH="$classpath"${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
export DYLD_LIBRARY_PATH="$classpath"${DYLD_LIBRARY_PATH:+:$DYLD_LIBRARY_PATH}

exec java -Xms1500M -Dfile.encoding=UTF-8 -cp "$classpath" org.icij.datashare.cli.DataShareCli $*
