#!/bin/bash

dir=`pwd $0`
dist_dir="${dir}/dist"

if [ ! -d "${dist_dir}" ]; then
    mkdir -p "${dist_dir}"
fi
classpath="${dir}/lib/*:${dist_dir}"

PATH=$PATH:"$classpath" \
LD_LIBRARY_PATH="$classpath"${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH} \
DYLD_LIBRARY_PATH="$classpath"${DYLD_LIBRARY_PATH:+:$DYLD_LIBRARY_PATH} \
java -Xms2000M -Dfile.encoding="UTF-8" -cp "$classpath" org.icij.datashare.cli.DataShareCli $*
