#!/bin/bash

dir=`pwd $0`

classpath="${dir}/lib/*"

PATH=$PATH:"$classpath" \
LD_LIBRARY_PATH="$classpath"${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH} \
DYLD_LIBRARY_PATH="$classpath"${DYLD_LIBRARY_PATH:+:$DYLD_LIBRARY_PATH} \
java -Xms1500M -Dfile.encoding="UTF-8" -cp "$classpath" org.icij.datashare.cli.DataShareCli $*
