application/mp4=VIDEO
application/pdf=DOCUMENT
application/msword=DOCUMENT
application/vnd.wordperfect=DOCUMENT
application/vnd.openxmlformats-officedocument.wordprocessingml.document=DOCUMENT
application/xml=DOCUMENT
text/plain=DOCUMENT
application/rtf=DOCUMENT
application/vnd.ms-word.document.macroenabled.12=DOCUMENT
application/vnd.oasis.opendocument.text=DOCUMENT
application/vnd.ms-word2006ml=DOCUMENT
application/vnd.openxmlformats-officedocument.wordprocessingml.template=DOCUMENT
application/vnd.ms-wordml=DOCUMENT
application/vnd.ms-word.template.macroenabled.12=DOCUMENT
application/vnd.ms-works=DOCUMENT
application/msword.document=DOCUMENT
application/vnd.ms-outlook=EMAIL
message/rfc822=EMAIL
application/vnd.ms-outlook-pst=EMAIL
application/x-corelpresentations=PRESENTATION
application/vnd.openxmlformats-officedocument.presentationml.presentation=PRESENTATION
application/vnd.ms-powerpoint=PRESENTATION
application/vnd.openxmlformats-officedocument.presentationml.slideshow=PRESENTATION
application/vnd.ms-powerpoint.presentation.macroenabled.12=PRESENTATION
application/vnd.ms-powerpoint.slideshow.macroenabled.12=PRESENTATION
application/vnd.ms-excel=SPREADSHEET
application/vnd.openxmlformats-officedocument.spreadsheetml.sheet=SPREADSHEET
application/vnd.ms-excel.sheet.macroenabled.12=SPREADSHEET
text/csv=SPREADSHEET
text/tsv=SPREADSHEET
application/vnd.ms-excel.sheet.binary.macroenabled.12=SPREADSHEET
application/x-tika-msworks-spreadsheet=SPREADSHEET
application/vnd.ms-spreadsheetml=SPREADSHEET
application/vnd.ms-excel.sheet.4=SPREADSHEET
application/x-msexcel=SPREADSHEET
application/vnd.ms-excel.template.macroenabled.12=SPREADSHEET
application/vnd.ms-excel.sheet.3=SPREADSHEET
