#!/usr/bin/env bash

dir=`pwd $0`

ES_VERSION="5.4.1"
ES_HOME="${dir}/opt/elasticsearch-${ES_VERSION}"
ES_INIT_FLAG="${ES_HOME}/config/datashare-init"

if [ -f ${ES_INIT_FLAG} ]; then
  exit 0
fi

echo "____________________"
echo "INDEX INITIALIZATION"
echo "____________________"

ES_PLUGINS_DIR="${ES_HOME}/plugins"
if [ -d ${ES_PLUGINS_DIR} ]; then
  mkdir ${ES_PLUGINS_DIR}
fi

sleep 7

echo "DEFINING TEMPLATE for *local* indices..."
curl -XPUT 'localhost:9200/_template/datashare_local_setting?pretty' -H 'Content-Type: application/json' -d '{
  "template": "*local*",
  "settings" : {
    "number_of_shards": 1,
    "number_of_replicas": 0
  }
}'

echo -e "\nDEFINING MAPPING for *datashare* indices..."
curl -XPUT 'localhost:9200/_template/datashare_mappings?pretty' -H 'Content-Type: application/json' -d '{
  "template": "datashare*",
  "mappings": {
    "SourcePath": {
      "properties": {
        "asOf": { "type": "date", "format": "date_time" },
        "path": { "type": "text" }
      }
    },
    "Document": {
      "properties": {
        "content": { "type": "text", "index_options": "offsets"},
        "asOf": { "type": "date", "format": "date_time" },
        "path": { "type": "text" },
        "length": { "type": "integer" },
        "encoding": { "type": "keyword" },
        "type": { "type": "keyword" },
        "language": { "type": "keyword" },
        "parser": { "type": "keyword" }
      }
    },
    "NamedEntity": {
      "_parent": { "type": "Document" },
      "properties": {
        "mention": { "type": "text", "index_options": "docs" },
        "mentionHash": { "type": "keyword" },
        "hash": { "type": "keyword" },
        "category": { "type": "keyword" },
        "document": { "type": "keyword" },
        "offset": { "type": "integer" },
        "extractor": { "type": "keyword" },
        "extractorLanguage": { "type": "keyword" },
        "partsOfSpeech": { "type": "text", "index_options": "docs" }
      }
    }
  }
}'

echo -e "\nCREATING INDEX datashare-local..."
curl -XPUT 'localhost:9200/datashare-local?pretty'

touch ${ES_INIT_FLAG}

echo "____________________"
echo "INDEX INITIALIZATION DONE"
echo "____________________"

sleep 3
