#!/bin/bash

dir=`pwd $0`

ES_VERSION="5.4.1"
ES_HOME="${dir}/opt/elasticsearch-${ES_VERSION}"

ES_JAVA_OPTS="-Xms1500M -Xmx1500M -Dfile.encoding=UTF-8" \
${ES_HOME}/bin/elasticsearch --pidfile "idx.pid" --daemonize

sleep 3

${dir}/init-idx
