#!/bin/bash

dir=`pwd $0`

ES_VERSION="5.4.1"

ES_JAVA_OPTS="-Xms1500M -Xmx1500M -Dfile.encoding=UTF-8" \
${dir}/opt/elasticsearch-${ES_VERSION}/bin/elasticsearch --pidfile "idx.pid" --daemonize

sleep 3

./init-idx

